import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import Layout from './components/layout';
import {Poppins} from 'next/font/google';
import {Roboto} from 'next/font/google';

const inter = Inter({subsets: ['latin']});
const roboto = Roboto({subsets: ['latin'], weight: '500'});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
